source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PandaFMDB_Example', :exclusive => true do
  pod 'PandaFMDB', :path => '../'
end

target 'PandaFMDB_Tests', :exclusive => true do
  pod 'PandaFMDB', :path => '../'

end
